### Buscar todos los coches disponibles
GET  http://rentacar-jmrb.herokuapp.com/api/v1/car/?available=1


### Filtrar coche por parámetros
GET  http://rentacar-jmrb.herokuapp.com/api/v1/car/?available=1&engine=diesel


### Ordenar coche por precio y limitar el número de registros que aparecen
GET  http://rentacar-jmrb.herokuapp.com/api/v1/car/price/?available=1&order=1&limit=2


### Ordenar coche por año y limitar el número de registros que aparecen
GET  http://rentacar-jmrb.herokuapp.com/api/v1/car/year/?available=1&order=1&limit=4


### Registro de admin (primera vez sólo)
POST http://rentacar-jmrb.herokuapp.com/api/v1/user/register
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin",
    "role": "admin"
}


### Registro de usuario
POST http://rentacar-jmrb.herokuapp.com/api/v1/user/register
Content-Type: application/json

{
    "email": "user@user.com",
    "password": "1234"
}


### Autenticación de usuario
POST http://rentacar-jmrb.herokuapp.com/api/v1/auth/login
Content-Type: application/json

{
    "email": "miemail2@user.com",
    "password": "1234"
}


### Autenticación de admin
POST http://rentacar-jmrb.herokuapp.com/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}


### Listado de usuarios
GET http://rentacar-jmrb.herokuapp.com/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzOTQ3MjE0OCwiZXhwIjoxNjM5NTU4NTQ4fQ.qCu6v_uUwfV5Uw2aw_m_SSxM6-4KDtcw-CLpEPo8EMo


### Actualización del perfil del usuario
PATCH http://rentacar-jmrb.herokuapp.com/api/v1/user/fcb32267-8958-4434-8410-c268c8edb686
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pZW1haWxAdXNlci5jb20iLCJpYXQiOjE2MzkzMDk4OTEsImV4cCI6MTYzOTM5NjI5MX0.gmWoqvKZqs_2ndjjsuDyxMy3-xOcPCy_4-I0BORU31s
Content-Type: application/json

{
    "license_num": "123456789A",
    "address": "10 Downing Street, London"
}


### Eliminación del perfil de un usuario
DELETE http://rentacar-jmrb.herokuapp.com/api/v1/user/fa04424a-9802-456d-a10e-8e53893203d4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzOTQ3MjYyNCwiZXhwIjoxNjM5NTU5MDI0fQ.dPjXo_UxjmuPgBaIJEsGCDWLnhNfVAf-muBpN44aSsI


### Adición de un coche (permiso admin)
POST http://rentacar-jmrb.herokuapp.com/api/v1/car
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzOTQ3NDY5NywiZXhwIjoxNjM5NTYxMDk3fQ.gthz2_-upbbMPojnqiDL5m19lkZDRxzhcXI8nVJDlKQ
Content-Type: application/json

{
    "brand": "Fiat",
    "model": "Punto",
    "year": 2018,
    "price_day": 15
}


### Actualización de la info de un coche (permiso admin)
PATCH  http://rentacar-jmrb.herokuapp.com/api/v1/car/dfe1bd77-a974-48d6-916f-f92d6aa893bf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzOTQ3NDY5NywiZXhwIjoxNjM5NTYxMDk3fQ.gthz2_-upbbMPojnqiDL5m19lkZDRxzhcXI8nVJDlKQ
Content-Type: application/json

{
    "engine": "diesel",
    "type": "tourism",
    "seats": 4,
    "autonomy": 700,
    "consum": 7,
    "bond": 600
}


### Eliminar un coche (permiso admin)
DELETE http://rentacar-jmrb.herokuapp.com/api/v1/car/235016d2-1042-4d76-bf1e-fb7219727167
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzOTEzODQxNywiZXhwIjoxNjM5MjI0ODE3fQ.uGo7aJQyLWYXj-UALjMs6PxiO5jOFUI95TyVoivT6wo


### Alquilar coche
POST http://rentacar-jmrb.herokuapp.com/api/v1/rental
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pZW1haWwyQHVzZXIuY29tIiwiaWF0IjoxNjM5NDc0MzAxLCJleHAiOjE2Mzk1NjA3MDF9.mF-VkCTZc1Wqad8qgfDdiVSJpOPZtOgMZomYqnGdjH4
Content-Type: application/json

{
    "carId": "613443d5-f901-443d-b6ac-84998c0a74e8",
    "userId": "d3014290-b273-4402-a22f-30790c49f94a",
    "start_date": "2021-12-15",
    "finish_date": "2021-12-22"
}


### Devolver coche (permiso admin)
PATCH http://rentacar-jmrb.herokuapp.com/api/v1/rental/74abeb98-7591-46f4-9e4b-3106902979af
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzOTM4ODgyMywiZXhwIjoxNjM5NDc1MjIzfQ.RViycsa1PibI9UC1ELcsKcGG7uZhKToFV3GC_lr7SZM
Content-Type: application/json

{
    "carId": "1862f335-fd2d-4b1e-b2c0-f3359da1c9f1",
    "userId": "e97539c5-5af1-46fe-bcbf-82bc04d42f9f"
}


### Listado de todas las reservas (permiso admin)
GET http://rentacar-jmrb.herokuapp.com/api/v1/rental/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzOTM5ODU4MCwiZXhwIjoxNjM5NDg0OTgwfQ.uyD3HcXK9ofWEw2tsK6vOwdXsUoIV3Hswkk4U0esNe4


### Mostrar una reserva (permiso admin)
GET http://rentacar-jmrb.herokuapp.com/api/v1/rental/7410f746-6828-4420-822a-94504e48ea69
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzOTM5ODU4MCwiZXhwIjoxNjM5NDg0OTgwfQ.uyD3HcXK9ofWEw2tsK6vOwdXsUoIV3Hswkk4U0esNe4


### Ordenar reservas por fecha de devolución (permiso admin)
GET http://rentacar-jmrb.herokuapp.com/api/v1/rental/retdate/?order=1&limit=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzOTM5ODU4MCwiZXhwIjoxNjM5NDg0OTgwfQ.uyD3HcXK9ofWEw2tsK6vOwdXsUoIV3Hswkk4U0esNe4


### Historial de reservas de un coche (permiso admin)
GET http://rentacar-jmrb.herokuapp.com/api/v1/rental/car/05484aaa-d551-4038-8746-01948c378570
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzOTM5ODU4MCwiZXhwIjoxNjM5NDg0OTgwfQ.uyD3HcXK9ofWEw2tsK6vOwdXsUoIV3Hswkk4U0esNe4


### Listado de todas las reservas de un cliente
GET http://rentacar-jmrb.herokuapp.com/api/v1/rental/user/6c0ae507-27a6-4916-8dde-9c78bc3c2412
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzOTM5ODU4MCwiZXhwIjoxNjM5NDg0OTgwfQ.uyD3HcXK9ofWEw2tsK6vOwdXsUoIV3Hswkk4U0esNe4