### Registro de usuario

POST http://localhost:3000/api/v1/user/register
Content-Type: application/json

{
    "email": "miemail2@user.com",
    "password": "1234"
}


### Autenticación de usuario

POST http://localhost:3000/api/v1/user/login
Content-Type: application/json

{
    "email": "miotro@mail.com",
    "password": "1234"
}

### Autenticación de usuario (con auth)

POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

### Actualización del perfil del usuario

PATCH http://localhost:3000/api/v1/user/6c0ae507-27a6-4916-8dde-9c78bc3c2412
Content-Type: application/json

{
    "address": "Calle Falso, 123",
    "license_num": "123456789AQ"
}

### Eliminación del perfil de un usuario

DELETE http://localhost:3000/api/v1/user/56351786-dcfa-4537-aaa0-ee813e604aff

### Adición de un coche

POST http://localhost:3000/api/v1/car
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzOTA1NjM0NiwiZXhwIjoxNjM5MTQyNzQ2fQ.lnxz3kbq3mMlI0VWILTscyjsAa5yQSms3kQMg4lHCtk

{
    "brand": "Renault",
    "model": "Megane",
    "year": 2020,
    "price_day": 20
}

### Actualización de la info de un coche

PATCH  http://localhost:3000/api/v1/car/5068ab90-c86a-4551-ba90-54d86b5f478f
Content-Type: application/json

{
    "engine": "diesel",
    "type": "tourism",
    "seats": 4,
    "autonomy": 700,
    "consum": 4,
    "bond": 800
}

### Eliminar un coche

DELETE http://localhost:3000/api/v1/car/237710f8-558b-4ce9-9549-ded6e74d3bbd

### Buscar todos los coches disponibles

GET  http://localhost:3000/api/v1/car/?available=1

### Filtrar por parámetros

GET  http://localhost:3000/api/v1/car/?available=1&engine=gasoline

### Ordenar por precio (o año) y limitar el número de registros que aparecen

GET  http://localhost:3000/api/v1/car/price/?available=1&order=1&limit=1

### Alquilar coche

POST http://localhost:3000/api/v1/rental
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pZW1haWxAdXNlci5jb20iLCJpYXQiOjE2MzgzNjU1MTksImV4cCI6MTYzODQ1MTkxOX0.KcZg4i7qShri-jrGQVGWXrrFibNTk5St5nwaW09QqW4
Content-Type: application/json

{
    "carId": "09b23725-eec2-4053-a06a-b95322adc4c4",
    "userId": "fcb32267-8958-4434-8410-c268c8edb686",
    "start_date": "2021-12-01",
    "finish_date": "2021-12-07"
}

### Devolver coche

PATCH http://localhost:3000/api/v1/rental/232cd8db-2c02-43c5-9e0b-f89ccac44d1d
Content-Type: application/json

{
    "carId": "09b23725-eec2-4053-a06a-b95322adc4c4",
    "userId": "fcb32267-8958-4434-8410-c268c8edb686"
}