### Registro de admin (primera vez sólo)

POST http://localhost:3000/api/v1/user/register
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

### Registro de usuario

POST http://localhost:3000/api/v1/user/register
Content-Type: application/json

{
    "email": "miemail@user.com",
    "password": "1234"
}

### Autenticación de usuario

POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "miemail@user.com",
    "password": "1234"
}

### Autenticación de admin

POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin"
}

### Actualización del perfil del usuario (user)

PATCH http://localhost:3000/api/v1/user/fcb32267-8958-4434-8410-c268c8edb686
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pZW1haWxAdXNlci5jb20iLCJpYXQiOjE2MzkzMDk4OTEsImV4cCI6MTYzOTM5NjI5MX0.gmWoqvKZqs_2ndjjsuDyxMy3-xOcPCy_4-I0BORU31s
Content-Type: application/json

{
    "email": "",
    "password": ""
}

### Eliminación del perfil de un usuario (user)

DELETE http://localhost:3000/api/v1/user/56351786-dcfa-4537-aaa0-ee813e604aff
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pZW1haWxAdXNlci5jb20iLCJpYXQiOjE2MzkzMDI5MjcsImV4cCI6MTYzOTM4OTMyN30.vUzIyMJ28CgT6xJSVPZBfZLnDamrcYVRY2LPUJcK4ew

### Adición de un coche (admin)

POST http://localhost:3000/api/v1/car
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pZW1haWxAdXNlci5jb20iLCJpYXQiOjE2MzkzMDI5MjcsImV4cCI6MTYzOTM4OTMyN30.vUzIyMJ28CgT6xJSVPZBfZLnDamrcYVRY2LPUJcK4ew
Content-Type: application/json

{
    "brand": "Renault",
    "model": "Megane",
    "year": 2020,
    "price_day": 20
}

### Actualización de la info de un coche (admin)

PATCH  http://localhost:3000/api/v1/car/5068ab90-c86a-4551-ba90-54d86b5f478f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pZW1haWxAdXNlci5jb20iLCJpYXQiOjE2MzkzMDI5MjcsImV4cCI6MTYzOTM4OTMyN30.vUzIyMJ28CgT6xJSVPZBfZLnDamrcYVRY2LPUJcK4ew
Content-Type: application/json

{
    "engine": "diesel",
    "type": "tourism",
    "seats": 4,
    "autonomy": 700,
    "consum": 4,
    "bond": 800
}

### Eliminar un coche (admin)

DELETE http://localhost:3000/api/v1/car/235016d2-1042-4d76-bf1e-fb7219727167
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzOTEzODQxNywiZXhwIjoxNjM5MjI0ODE3fQ.uGo7aJQyLWYXj-UALjMs6PxiO5jOFUI95TyVoivT6wo

### Buscar todos los coches disponibles

GET  http://localhost:3000/api/v1/car/?available=1

### Filtrar coche por parámetros

GET  http://localhost:3000/api/v1/car/?available=1&engine=gasoline

### Ordenar coche por precio (o año) y limitar el número de registros que aparecen

GET  http://localhost:3000/api/v1/car/price/?available=1&order=1&limit=1

### Alquilar coche (user)

POST http://localhost:3000/api/v1/rental
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1pZW1haWxAdXNlci5jb20iLCJpYXQiOjE2MzkzMDI5MjcsImV4cCI6MTYzOTM4OTMyN30.vUzIyMJ28CgT6xJSVPZBfZLnDamrcYVRY2LPUJcK4ew
Content-Type: application/json

{
    "carId": "09b23725-eec2-4053-a06a-b95322adc4c4",
    "userId": "fcb32267-8958-4434-8410-c268c8edb686",
    "start_date": "2021-12-15",
    "finish_date": "2021-12-22"
}

### Devolver coche (admin)

PATCH http://localhost:3000/api/v1/rental/c20005ee-7721-46eb-bbea-a07dfc8878d6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlhdCI6MTYzOTMwNjE5NiwiZXhwIjoxNjM5MzkyNTk2fQ.YMahe1b4uI6c7Dhhf9z3JWuJGHN-96wPMCzsr70P6Bw

{
    "carId": "09b23725-eec2-4053-a06a-b95322adc4c4",
    "userId": "fcb32267-8958-4434-8410-c268c8edb686"
}